 

   <div class="container"> <div class="row"> <div class="senja-embed" data-id="1dbfe1ba-fe93-44ce-8d79-6dfccef7fc47" data-mode="shadow" data-lazyload="false" data-built="true" data-session="6301209a-6869-42e2-a071-a12c02d3045b"></div> <script async="" type="text/javascript" src="https://widget.senja.io/widget/1dbfe1ba-fe93-44ce-8d79-6dfccef7fc47/platform.js"></script> </div> <div class="row mt-5"> <div class="col-lg-6"> <h4 class="text-white">TCG Land</h4> <p class="text-light text-opacity-50 mt-2">
Tu tienda Mexicana con +80,000 cartas de Magic: The Gathering...<br>
...y pronto Pokémon y Yu-Gi-Oh! + toda América Latina.
</p> <ul class="list-unstyled mt-3"> <li> <a class="text-light text-opacity-50" target="_blank" href="https://ayuda.tcg.land/ayuda/politica-de-privacidad-de-tcg-land/">Política de privacidad</a> </li> <li> <a class="text-light text-opacity-50" target="_blank" href="https://ayuda.tcg.land/ayuda/terminos-y-condiciones-de-tcg-land/">Términos y Conditions</a> </li> <li> <a class="text-light text-opacity-50" target="_blank" href="https://ayuda.tcg.land/ayuda/politica-de-cookies-de-tcg-land/">Política de Cookie</a> </li> </ul> </div> <div class="col-lg-2 col-md-4 mt-3 mt-lg-0"> <h5 class="text-light">Ayuda</h5> <ul class="list-unstyled ps-0 mb-0 mt-3"> <li> <a target="_blank" class="text-light text-opacity-50" href="https://ayuda.tcg.land/ayuda/horarios-de-atencion-y-tiempo-de-respuesta-del-servicio-al-cliente-de-tcg-land/">Atención al cliente</a> </li> <li> <a target="_blank" class="text-light text-opacity-50" href="https://ayuda.tcg.land/">FAQs</a> </li> <li> <a target="_blank" class="text-light text-opacity-50" href="https://ayuda.tcg.land/ayuda/politica-de-devoluciones-y-reembolsos-de-tcg-land/">Política de Reembolsos y Devoluciones</a> </li> <li> <a target="_blank" class="text-light text-opacity-50" href="https://ayuda.tcg.land/ayuda/programa-de-afiliados-de-tcg-land/">Programa de Afiliados</a> </li> <li> <a target="_blank" class="text-light text-opacity-50" href="https://developers.tcg.land/es">API y Volcado de datos</a> </li> </ul> </div> <div class="col-lg-2 col-md-4 mt-3 mt-lg-0"> <h5 class="text-light">Compra</h5> <ul class="list-unstyled ps-0 mb-0 mt-3"> <li> <a class="text-light text-opacity-50" href="/multisearch#/magic-the-gathering">
Búsqueda Múltiple
</a> </li> <li> <a target="_blank" class="text-light text-opacity-50" href="/search#/magic-the-gathering">Magic: The Gathering </a> </li> <li class="mt-3"> <span class="text-light text-opacity-50">Próximamente: </span> </li> <li> <span class="text-light text-opacity-50">Yu-Gi-Oh!</span> </li> <li> <span class="text-light text-opacity-50">Pokémon</span> </li> </ul> </div> <div class="col-lg-2 col-md-4 mt-3 mt-lg-0"> <h5 class="text-light">Contacto</h5> <ul class="list-unstyled ps-0 mb-0 mt-3"> <li class="mt-3"> <a aria-label="Chat on WhatsApp" href="https://wa.me/525547935013" target="_blank"> <img alt="Chat on WhatsApp" src="/_astro/whatsapp.DMI3br3m.svg"> </a> </li> <li class="mt-3"> <a class="text-light text-opacity-50" href="mailto:info@tcg.land" target="_blank">info@tcg.land</a> </li> </ul> <br> <h5 class="text-light">Síguenos en Redes</h5> <ul class="list-unstyled ps-0 mb-0 mt-2"> <li> <a href="https://www.instagram.com/reel/C8kxMs_PyiV/" class="fs-2 text-light text-opacity-50" target="_blank"> <i class="ri-instagram-line"></i> </a> <a href="https://www.facebook.com/tcg.land.fb/" class="fs-2 text-light text-opacity-50" target="_blank"> <i class="ri-facebook-circle-fill"></i> </a> <a href="https://www.tiktok.com/@tcg.land" class="fs-2 text-light text-opacity-50" target="_blank"> <i class="ri-tiktok-fill"></i> </a> <a href="https://www.youtube.com/@tcg-land" class="fs-2 text-light text-opacity-50" target="_blank"> <i class="ri-youtube-fill"></i> </a> <a href="https://discord.gg/YKbJzkNvWR" class="fs-2 text-light text-opacity-50" target="_blank"> <i class="ri-discord-fill"></i> </a> </li> </ul> </div> </div> <div class="row mt-5"> <div class="col"> <p class="mb-3 mb-md-0 fs-xxs text-muted">
2024 TCG Land, SAPI de CV - Todos los Derechos Reservados
</p> <p class="mb-3 mb-md-0 fs-xxs text-muted">
Last deployment: Wed, 7 Aug 2024 06:09 +00:00 </p> <p class="mb-3 mb-md-0 fs-xxs text-muted">
Revision: main f4199e8dd32b4d9206b3bc8b6a9668e7e38c6ccd </p> </div> <div class="col-auto"> <img class="footer-payment" src="/_astro/mastercard.DZPkINsw.svg" alt="..."> <img class="footer-payment" src="/_astro/visa.LSjQMW8S.svg" alt="..."> <img class="footer-payment" src="/_astro/amex.--xHQWOX.svg" alt="..."> <img class="footer-payment" src="/_astro/paypal.DjpH6tr3.svg" alt="..."> <img class="footer-payment" src="/_astro/maestro.ZyvNBdnU.svg" alt="..."> <img class="footer-payment" src="/_astro/klarna.CKl9LKC7.svg" alt="..."> </div> </div> </div> 